// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iehrgkujambjgmbjhdhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllaHJna3VqYW1iamdtYmpoZGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTcwMDgsImV4cCI6MjA3MTY5MzAwOH0.IaKobrH2smaV2JwBAvVeyMS0pw5iCnTlOKw4FumXYDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});